version: '{build}'

clone_folder: c:\projects\open62541

# Do not set clone depth, we need all the tags to automatically detect the version based on git describe
# clone_depth: 20

# Avoid building branch if it is part of a PR and built anyways
skip_branch_with_pr: true

# Fast finish (stop other builds if one fails) to speed up appveyor builds
matrix:
  fast_finish: true

environment:
    global:
        APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9

    matrix:
        - CC_NAME: Visual Studio 9 2008
          CC_SHORTNAME: vs2008
          GENERATOR: Visual Studio 9 2008
          FORCE_CXX: ON
        - CC_NAME: Visual Studio 12 2013
          CC_SHORTNAME: vs2013
          GENERATOR: Visual Studio 12 2013
          FORCE_CXX: OFF

cache:
  - C:\ProgramData\chocolatey\bin -> tools/appveyor/install.ps1
  - C:\ProgramData\chocolatey\lib -> tools/appveyor/install.ps1
  - C:\tools\vcpkg\installed -> tools/appveyor/install.ps1

init:
  - git config --global core.autocrlf input # Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail

install:
- set PATH=C:\Users\appveyor\AppData\Roaming\Python\Scripts;%PATH%
- ps: '& "./tools/appveyor/install.ps1"'

build_script:
- ps: '& "./tools/appveyor/build.ps1"'

after_build:
  # Only push artifact if make install is defined
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-static.zip
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\open62541-%CC_SHORTNAME%-dynamic.zip
