# Docs see here:
# https://aka.ms/yaml

jobs:
- job: 'cross_freeRTOS'
  displayName: 'Arch (freeRTOS)'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    IDF_PATH: $(Build.BinariesDirectory)/esp-idf
  steps:
  - checkout: self
    submodules: recursive

  - task: Bash@3
    inputs:
      targetType: FilePath
      filePath: ./tools/azure-devops/freeRTOS/install.sh
      failOnStderr: false
    displayName: Installing required packages

  - task: Bash@3
    inputs:
      targetType: FilePath
      filePath: ./tools/azure-devops/freeRTOS/build.sh
      failOnStderr: false
    displayName: Building & Testing

